### ISSUE TITLE
Tabbar Button declare is not clear

### ISSUE THREAD

**Issue by amirsaam** [exyte/AnimatedTabBar#10]
Hello there,
Thanks for your effort on the package but unfortunately your example app is not quietly understandable for newbies.
Can you provide a simple declare for Tabbar Buttons?
What should exactly put in the below closure?
```swift
AnimatedTabBar(selectedIndex: $selectedTab, prevSelectedIndex: $previousTab) {

}
```
and how should we bind the buttons to show correct view?

p.s: If a complex implementation such what you did in the example app is needed, I think it is better to have in inside the package itself with a clear definition and more simple struct like:
```swift
AnimatedTabBarItem(icon: Image, view: AnyView)
```
to let us pass the view needed to be shown with the item itself.

**Comment by f3dm76** [comment]
Hey @amirsaam, as the readme says - you can pass any views you like. You don't have to do anything to bind them, that is what the library does.
```
import SwiftUI
import AnimatedTabBar

@main
struct ExampleApp: App {

    @State var sel = 0
    @State var selPrev = 0

    var body: some Scene {
        WindowGroup {
            AnimatedTabBar(selectedIndex: $sel, prevSelectedIndex: $selPrev) {
                Image(systemName: "circle")
                Image(systemName: "rectangle")
                Image(systemName: "square")
            }
        }
    }
}
```
Have a nice day

**Comment by amirsaam** [comment]
@f3dm76 Thanks for the reply but then there is an issue I think?
```swift
      AnimatedTabBar(
        selectedIndex: $selectedTab,
        prevSelectedIndex: $previousTab
      ) {
        ForEach(Tabs.allCases, id: \.rawValue) { tab in
          Image(systemName: tab.tabIcon)
        }
      }
```
this does not work.
Also, I think you need to clarify in the how to use section that we need 
```swift
      TabView(selection: $selectedTab) {
        View1().tag(0)
        View2().tag(1)
        View3().tag(2)
        View4().tag(3)
      }
```

**Comment by amirsaam** [comment]
@f3dm76 
this is an example enum:
```swift
enum Tabs: Int, CaseIterable {
  case timeline, lists, spaces, miscs, profile
  
  var tabIcon: String {
    switch self {
    case .timeline: return "house"
    case .lists: return "scroll"
    case .spaces: return "radio"
    case .miscs: return "circle.grid.2x2"
    case .profile: return "person"
    }
  }
  var buttonIcon: String {
    switch self {
    case .timeline, .lists: return "plus"
    case .spaces: return "mic.fill"
    case .miscs: return "envelope.fill"
    case .profile: return "gearshape.fill"
    }
  }
}
```
but it does not matter, because you cannot use any loop in `AnimatedTabBar`.
But I cannot understand how you say I don't need the TabView
This is w/o TabView:
![IMG_4223](https://github.com/user-attachments/assets/89096617-35a0-4616-bc29-8d0a31d5f4aa)
This is w/ TabView:
![IMG_4224](https://github.com/user-attachments/assets/376b394b-2388-4ee1-9601-aa1e7c10ee73)
This is my whole code for the root view:
```swift
    ZStack(alignment: .bottom) {
      TabView(selection: $selectedTab) {
        PlayView().tag(0)
        ScenariosView().tag(1)
        RolesView().tag(2)
        SettingsView(moderatorIsNotDefined: $moderatorIsNotDefined).tag(3)
      }
      AnimatedTabBar(
        selectedIndex: $selectedTab,
        prevSelectedIndex: $previousTab
      ) {
        Image("play", bundle: .radixUI)
          .resizable()
          .aspectRatio(contentMode: .fit)
          .frame(width: 25)
          .scaleEffect(selectedTab == 0 ? 1.2 : 1.0)
          .onTapGesture {
            withAnimation(.easeInOut(duration: 0.4)) {
              selectedTab = 0
            }
          }
        Image("archive", bundle: .radixUI)
          .resizable()
          .aspectRatio(contentMode: .fit)
          .frame(width: 25)
          .scaleEffect(selectedTab == 1 ? 1.2 : 1.0)
          .onTapGesture {
            withAnimation(.easeInOut(duration: 0.4)) {
              selectedTab = 1
            }
          }
        Image("card-stack", bundle: .radixUI)
          .resizable()
          .aspectRatio(contentMode: .fit)
          .frame(width: 25)
          .scaleEffect(selectedTab == 2 ? 1.2 : 1.0)
          .onTapGesture {
            withAnimation(.easeInOut(duration: 0.4)) {
              selectedTab = 2
            }
          }
        Image("gear", bundle: .radixUI)
          .resizable()
          .aspectRatio(contentMode: .fit)
          .frame(width: 25)
          .scaleEffect(selectedTab == 3 ? 1.2 : 1.0)
          .onTapGesture {
            withAnimation(.easeInOut(duration: 0.4)) {
              selectedTab = 3
            }
          }
      }
      .barColor(blackWhite)
      .selectedColor(whiteBlack)
      .unselectedColor(.gray11)
      .ballColor(blackWhite)
      .ballAnimation(.interpolatingSpring)
      .ballTrajectory(.parabolic)
      .cornerRadius(15)
      .verticalPadding(30)
      .padding(.horizontal)
    }
```

**Comment by amirsaam** [comment]
Update:

I can confirm that this does work:
```swift
let tabIcons = ["play", "archive", "card-stack", "gear"]
AnimatedTabBar(
  selectedIndex: $selectedTab,
  prevSelectedIndex: $previousTab,
  views: (0..<tabIcons.count).map { tab in
    Image(tabIcons[tab], bundle: .radixUI)
      .resizable()
      .aspectRatio(contentMode: .fit)
      .frame(width: 20)
      .scaleEffect(selectedTab == tab ? 1.2 : 1.0)
      .onTapGesture {
        withAnimation(.easeInOut(duration: 0.4)) {
          selectedTab = tab
        }
      }
  }
)
.barColor(blackWhite)
.selectedColor(whiteBlack)
.unselectedColor(.gray11)
.ballColor(blackWhite)
.ballAnimation(.interpolatingSpring)
.ballTrajectory(.parabolic)
.cornerRadius(15)
.verticalPadding(25)
.padding(.horizontal)
```
But to be honest, I still prefer to use a ForEach in the `AnimatedTabBar(selectedIndex: $selectedTab, prevSelectedIndex: $previousTab) { HERE }` closure.

**Comment by f3dm76** [comment]
> But to be honest, I still prefer to use a ForEach
Me too, but Apple only introduces such API in swift 6. There is no way to pass a ForEach and then iterate through the views in my framework - it is completely type erased and considered as one view. So this was the best I could do. Please do commit a PR is you can overcome this restriction.

> I do still need the TabView mentioned before to bind my views
I do not understand - why do you need a TabView at all?

struct ContentView: View {

    @State var selectedTab = 0
    @State var previousTab = 0

    var body: some View {
        ZStack(alignment: .bottom) {
            switch selectedTab {
            case 0: Color.green
            case 1: Color.blue
            case 2: Color.yellow
            default: Color.teal
            }

            AnimatedTabBar(
                selectedIndex: $selectedTab,
                prevSelectedIndex: $previousTab
            ) {
                tab(0, "play")
                tab(1, "circle")
                tab(2, "play")
                tab(3, "play")
            }
        }
    }

    func tab(_ index: Int, _ name: String) -> some View {
        Image(systemName: name)
            .resizable()
            .aspectRatio(contentMode: .fit)
            .frame(width: 25)
            .scaleEffect(selectedTab == index ? 1.2 : 1.0)
            .animation(.easeInOut(duration: 0.4), value: selectedTab)
    }
}

**Comment by amirsaam** [comment]
@f3dm76 thanks for your example, now I somehow understand how the showing views work.

> Please do commit a PR if you can overcome this restriction.

I'm still getting familiar with your framework but surely with more knowledge about it, I will try to do such.

> I do not understand - why do you need a TabView at all?

I used Tabview because I had no idea how exactly you intended to this framework work and the switch case in a zstack was not mentioned in neither of example app or readme, I think it is better to replace
```swift
import AnimatedTabBar

AnimatedTabBar(selectedIndex: $selectedIndex) {
    TabButton1()
    TabButton2()
    TabButton3()
}
```
with your example and also the second one with more simple example like
```swift
let tabIcons = ["plus", "circle", "person", "gear"]
AnimatedTabBar(
  selectedIndex: $selectedTab,
  prevSelectedIndex: $previousTab,
  views: (0..<tabIcons.count).map { index in
    Image(systemName: tabIcons[index])
  }
)
```

> AnyView has a lot of downsides

Surely you done more tests and vast experience with your package, passing AnyView was a simple option to let developers easily create Tabs.

Kudos to you and Exyte team, I will close this issue but please update readme.
Regards.
