### ISSUE TITLE
Variable 'self.views' used before being initialized

### ISSUE THREAD

**Issue by graygillman** [exyte/AnimatedTabBar#15]
Recently been running into this issue which is breaking my entire App and the only way for me to get it to work is by removing the AnimatedTabBar package. Let me know if you find a fix to this issue.

`public struct AnimatedTabBar: View {

    public enum BallTrajectory {
        case parabolic
        case teleport
        case straight
    }

    @Binding private var selectedIndex: Int
    @Binding private var prevSelectedIndex: Int
    private let views: [AnyView]

    public init<Views>(selectedIndex: Binding<Int>,
                       prevSelectedIndex: Binding<Int>? = nil,
                       @ViewBuilder content: @escaping () -> TupleView<Views>) {
        self._selectedIndex = selectedIndex
        self._prevSelectedIndex = prevSelectedIndex ?? .constant(0)
        self.internalPrevSelectedIndex = selectedIndex.wrappedValue
        self.views = content().getViews
    }

    public init<Content: View>(selectedIndex: Binding<Int>,
                               prevSelectedIndex: Binding<Int>? = nil,
                               views: [Content]) {
        self._selectedIndex = selectedIndex
        self._prevSelectedIndex = prevSelectedIndex ?? .constant(0)
        self.internalPrevSelectedIndex = selectedIndex.wrappedValue
        self.views = views.map { AnyView($0) }
    }public struct AnimatedTabBar: View {

    public enum BallTrajectory {
        case parabolic
        case teleport
        case straight
    }

    @Binding private var selectedIndex: Int
    @Binding private var prevSelectedIndex: Int
    private let views: [AnyView]

    public init<Views>(selectedIndex: Binding<Int>,
                       prevSelectedIndex: Binding<Int>? = nil,
                       @ViewBuilder content: @escaping () -> TupleView<Views>) {
        self._selectedIndex = selectedIndex
        self._prevSelectedIndex = prevSelectedIndex ?? .constant(0)
        self.internalPrevSelectedIndex = selectedIndex.wrappedValue
        self.views = content().getViews
    }

    public init<Content: View>(selectedIndex: Binding<Int>,
                               prevSelectedIndex: Binding<Int>? = nil,
                               views: [Content]) {
        self._selectedIndex = selectedIndex
        self._prevSelectedIndex = prevSelectedIndex ?? .constant(0)
        self.internalPrevSelectedIndex = selectedIndex.wrappedValue
        self.views = views.map { AnyView($0) }
    }'

**Comment by f3dm76** [comment]
@graygillman, thanks for the heads up, fixed in version 0.1.4

**Comment by graygillman** [comment]
Thanks!
