### ISSUE TITLE
Unable to use binding

### ISSUE THREAD

**Issue by Benetos** [exyte/AnimatedTabBar#3]
Just downloaded the library and was setting up a basic tab bar to mess around with.

`import SwiftUI
import AnimatedTabBar

struct AnimatedTabBar: View {
    @State var selectedIndex = 0
    var body: some View {
        AnimatedTabBar(selectedIndex: $selectedIndex)
    }
}

struct AnimatedTabBar_Previews: PreviewProvider {
    static var previews: some View {
        AnimatedTabBar()
    }
}`

However it is producing an error saying "Cannot convert value '$selectedIndex' of type 'Binding<Int>' to expected type 'Int', use wrapped value instead" and it wants me to to remove the binding. If I remove the binding the error goes away but I get a crash when I try to run the preview in the canvas.

**Comment by f3dm76** [comment]
Hey @Benetos I think the problem might be that you are using the same name for your struct 'AnimatedTabBar'. Have a nice day
