### ISSUE TITLE
Canvas Crash

### ISSUE THREAD

**Issue by Benetos** [exyte/AnimatedTabBar#4]
When I attempt to run the canvas to preview a basic tab bar it is crashing...

`import SwiftUI
import AnimatedTabBar

struct AnimatedTabBar: View {
    @State var selectedIndex = 0
    var body: some View {
        AnimatedTabBar(selectedIndex: $selectedIndex)
    }
}

struct AnimatedTabBar_Previews: PreviewProvider {
    static var previews: some View {
        AnimatedTabBar()
    }
}`

Here is the crash log...
[Faith Church Prayer-2023-05-31-120535.txt](https://github.com/exyte/AnimatedTabBar/files/11616874/Faith.Church.Prayer-2023-05-31-120535.txt)

**Comment by f3dm76** [comment]
Same as https://github.com/exyte/AnimatedTabBar/issues/3

**Comment by Benetos** [comment]
Yeah. 

Apologies I meant to come back and update this but got sidetracked. I didn't realized I had just naturally picked the same name for the extract so when I did and changed it things are working as intended.
